# Generated by Django 5.0.4 on 2024-04-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthentication',
            name='cam_settings',
        ),
    ]
