# Generated by Django 5.0.4 on 2024-04-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold', models.FloatField(blank=True, default=0.5, null=True)),
                ('segmentation_orientation', models.CharField(blank=True, max_length=1, null=True)),
                ('point1X', models.IntegerField(default=0)),
                ('point1Y', models.IntegerField(default=0)),
                ('point2X', models.IntegerField(default=0)),
                ('point2Y', models.IntegerField(default=0)),
                ('area_flipped', models.BooleanField(default=False)),
            ],
        ),
    ]
