# Generated by Django 5.0.4 on 2024-04-17 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0001_initial'),
        ('token_authentication', '0002_remove_userauthentication_cam_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold', models.FloatField(blank=True, default=0.5, null=True)),
                ('segmentation_orientation', models.CharField(blank=True, max_length=1, null=True)),
                ('point1X', models.IntegerField(default=0)),
                ('point1Y', models.IntegerField(default=0)),
                ('point2X', models.IntegerField(default=0)),
                ('point2Y', models.IntegerField(default=0)),
                ('area_flipped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='token_authentication.userauthentication')),
            ],
        ),
        migrations.CreateModel(
            name='InferenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='rtdetr_yolov9bb_ep27.onnx', max_length=100)),
                ('overlay_line', models.CharField(default='h_0_450_640_450_0', max_length=100)),
                ('obj_warning', models.CharField(default='person,bicycle', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='token_authentication.userauthentication')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='CamSettings',
        ),
    ]
