# Generated by Django 5.0.4 on 2024-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0003_delete_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencesettings',
            name='size',
            field=models.IntegerField(default=640),
        ),
    ]
