# Generated by Django 5.0.4 on 2024-04-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0004_inferencesettings_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inferencesettings',
            old_name='obj_warning',
            new_name='objects_to_warn',
        ),
    ]
