# Generated by Django 5.0.4 on 2024-04-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0005_rename_obj_warning_inferencesettings_objects_to_warn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesettings',
            name='point2X',
        ),
        migrations.RemoveField(
            model_name='homesettings',
            name='point2Y',
        ),
    ]
