# Generated by Django 5.0.4 on 2024-04-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0006_remove_homesettings_point2x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesettings',
            name='segmentation_orientation',
        ),
    ]
