# Generated by Django 5.0.4 on 2024-04-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0007_remove_homesettings_segmentation_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='segmentation_orientation',
            field=models.CharField(blank=True, default='h', max_length=1, null=True),
        ),
    ]
