# Generated by Django 5.0.4 on 2024-04-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0008_homesettings_segmentation_orientation'),
        ('token_authentication', '0002_remove_userauthentication_cam_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objs', models.CharField(default='', max_length=200)),
                ('frame_path', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='token_authentication.userauthentication')),
            ],
        ),
    ]
