# Generated by Django 5.0.4 on 2024-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0009_warningnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencesettings',
            name='thrh',
            field=models.FloatField(default=0.55),
        ),
    ]
