# Generated by Django 5.0.4 on 2024-04-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrusion_detection', '0010_inferencesettings_thrh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesettings',
            name='area_flipped',
        ),
        migrations.RemoveField(
            model_name='homesettings',
            name='model',
        ),
        migrations.RemoveField(
            model_name='homesettings',
            name='point1X',
        ),
        migrations.RemoveField(
            model_name='homesettings',
            name='point1Y',
        ),
        migrations.RemoveField(
            model_name='homesettings',
            name='segmentation_orientation',
        ),
        migrations.RemoveField(
            model_name='homesettings',
            name='threshold',
        ),
        migrations.AlterField(
            model_name='inferencesettings',
            name='overlay_line',
            field=models.CharField(blank=True, default='h_0_400_0', max_length=50, null=True),
        ),
    ]
